@set allusersprofile=c:\programdata
@set amdappsdkroot=c:\program files (x86)\amd app\
@set appdata=c:\users\???\appdata\roaming;C:\Users\Антон\AppData\Roaming
@set cm2013dir=c:\program files (x86)\common files\autodesk shared\materials\
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=anton-pc
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio 12.0\common7\ide\
@set dxsdk_dir=c:\program files (x86)\microsoft directx sdk (june 2010)\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows\v8.1\extensionsdks
@set fp_no_host_check=no
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft sdks\f#\3.1\framework\v4.0\
@set homedrive=c:
@set homepath=\users\???;\Users\Антон
@set ilbdir=c:\program files (x86)\common files\autodesk shared\materials\
@set include=c:\program files (x86)\microsoft visual studio 12.0\vc\include;c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include;c:\program files (x86)\windows kits\8.1\include\shared;c:\program files (x86)\windows kits\8.1\include\um;c:\program files (x86)\windows kits\8.1\include\winrt
@set lib=c:\program files (x86)\microsoft visual studio 12.0\vc\lib;c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\lib\winv6.3\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 12.0\vc\lib;c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral;c:\program files (x86)\microsoft sdks\windows\v8.1\extensionsdks\microsoft.vclibs\12.0\references\commonconfiguration\neutral
@set localappdata=c:\users\???\appdata\local;C:\Users\Антон\AppData\Local
@set logonserver=\\anton-pc
@set moz_plugin_path=d:\prog\tracker software\pdf viewer\win32\
@set msbuildloadmicrosofttargetsreadonly=true
@set number_of_processors=6
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio 12.0\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft sdks\f#\3.1\framework\v4.0\;c:\program files (x86)\msbuild\12.0\bin;c:\program files (x86)\microsoft visual studio 12.0\common7\ide\;c:\program files (x86)\microsoft visual studio 12.0\vc\bin;c:\program files (x86)\microsoft visual studio 12.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 12.0\vc\vcpackages;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 12.0\team tools\performance tools;c:\program files (x86)\windows kits\8.1\bin\x86;c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\;c:\program files (x86)\amd app\bin\x86_64;c:\program files (x86)\amd app\bin\x86;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\ati technologies\ati.ace\core-static;c:\program files\microsoft windows performance toolkit\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files (x86)\skype\phone\;c:\program files (x86)\common files\autodesk shared\;c:\program files (x86)\backburner 2\;d:\prog\3dsmax7\;c:\program files (x86)\common files\autodesk shared\;c:\program files\tortoisesvn\bin;c:\program files (x86)\nvidia corporation\physx\common
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\???\appdata\local\microsoft\visualstudio\12.0\devenv.exe.config;C:\Users\Антон\AppData\Local\Microsoft\VisualStudio\12.0\devenv.exe.config
@set processor_architecture=amd64
@set processor_identifier=amd64 family 21 model 2 stepping 0, authenticamd
@set processor_level=21
@set processor_revision=0200
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\
@set public=c:\users\public
@set sessionname=console
@set stcore32=c:\program files\sview\
@set stcore64=c:\program files\sview\amd64\
@set stshare=c:\program files\sview\
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\3ec2~1\appdata\local\temp
@set tmp=c:\users\3ec2~1\appdata\local\temp
@set userdomain=anton-pc
@set username=???;Антон
@set userprofile=c:\users\???;C:\Users\Антон
@set vbox_msi_install_path=g:\program files\oracle\virtualbox\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 12.0\vc\
@set visualstudiodir=c:\users\???\documents\visual studio 2013;C:\Users\Антон\Documents\Visual Studio 2013
@set visualstudioedition=microsoft visual studio ultimate 2013
@set visualstudioversion=12.0
@set vs100comntools=c:\program files (x86)\microsoft visual studio 10.0\common7\tools\
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=c:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 12.0\
@set vslang=1033
@set windir=c:\windows
@set windowssdkdir=c:\program files (x86)\windows kits\8.1\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\

@call "C:\Program Files (x86)\PVS-Studio\x86\clang.exe" @"C:\X-Ray_Engine_1.5.1.0\src\xrGame\CameraFirstEye.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1